const quijoteFrases = [
  "En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho tiempo que vivÃ­a un hidalgo de los de lanza en astillero, adarga antigua, rocÃ­n flaco y galgo corredor.",
  "Una olla de algo mÃ¡s vaca que carnero, salpicÃ³n las mÃ¡s noches, duelos y quebrantos los sÃ¡bados, lentejas los viernes, algÃºn palomino de aÃ±adidura los domingos, consumÃ­an las tres partes de su hacienda.",
  "El resto della concluÃ­an sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mesmo, los dÃ­as de entre semana se honraba con su vellorÃ­ de lo mÃ¡s fino.",
  "TenÃ­a en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que asÃ­ ensillaba el rocÃ­n como tomaba la podadera.",
  "Frisaba la edad de nuestro hidalgo con los cincuenta aÃ±os; era de complexiÃ³n recia, seco de carnes, enjuto de rostro, gran madrugador y amigo de la caza.",
  "Quieren decir que tenÃ­a el sobrenombre de Quijada, o Quesada, que en esto hay alguna diferencia en los autores que deste caso escriben; aunque, por conjeturas verosÃ­miles, se deja entender que se llamaba Quijana.",
  "Pero esto importa poco a nuestro cuento; basta que en la narraciÃ³n dÃ©l no se salga un punto de la verdad.",
  "Es, pues, de saber que este sobredicho hidalgo, los ratos que estaba ocioso, que eran los mÃ¡s del aÃ±o, se daba a leer libros de caballerÃ­as, con tanta aficiÃ³n y gusto, que olvidÃ³ casi de todo punto el ejercicio de la caza, y aun la administraciÃ³n de su hacienda.",
  "Y llegÃ³ a tanto su curiosidad y desatino en esto, que vendiÃ³ muchas hanegas de tierra de sembradura, para comprar libros de caballerÃ­as en que leer; y asÃ­ llevÃ³ a su casa todos cuantos pudo haber dellos.",
  "Y de todos ningunos le parecÃ­an tan bien como los que compuso el famoso Feliciano de Silva, porque la claridad de su prosa y aquellas intrincadas razones suyas le parecÃ­an de perlas.",
  "Especialmente cuando llegaba a leer aquellos requiebros y cartas de desafÃ­os, donde en muchas partes hallaba escrito: la razÃ³n de la sinrazÃ³n que a mi razÃ³n se hace, de tal manera mi razÃ³n enflaquece, que con razÃ³n me quejo de la vuestra fermosura.",
  "Con estas razones perdÃ­a el pobre caballero el juicio, y desvelÃ¡base por entenderlas y desentraÃ±arles el sentido, que no se lo sacara ni las entendiera el mismo AristÃ³teles, si resucitara para sÃ³lo ello.",
  "No estaba muy bien con las heridas que don BelianÃ­s daba y recibÃ­a, porque se imaginaba que, por grandes maestros que le hubiesen curado, no dejarÃ­a de tener el rostro y todo el cuerpo lleno de cicatrices y seÃ±ales.",
  "Pero con todo alababa en su autor aquel acabar su libro con la promesa de aquella inacabable aventura; y muchas veces le vino deseo de tomar la pluma y darle fin al pie de la letra, como allÃ­ se promete.",
  "Y sin duda alguna lo hiciera, y aun saliera con ello, si otros mayores y continuos pensamientos no se lo estorbaran.",
  "Tuvo muchas veces competencia con el cura de su lugar (que era hombre docto, graduado en SigÃ¼enza), sobre cuÃ¡l habÃ­a sido mejor caballero: PalmerÃ­n de Inglaterra o AmadÃ­s de Gaula.",
  "Mas maese NicolÃ¡s, barbero del mismo pueblo, decÃ­a que ninguno llegaba al caballero del Febo, y que si alguno se le podÃ­a comparar, era don Galaor, hermano de AmadÃ­s de Gaula, porque tenÃ­a muy acomodada condiciÃ³n para todo.",
  "En resoluciÃ³n, Ã©l se enfrascÃ³ tanto en su lectura, que se le pasaban las noches leyendo de claro en claro, y los dÃ­as de turbio en turbio, y asÃ­, del poco dormir y del mucho leer, se le secÃ³ el cerebro, de manera que vino a perder el juicio.",
  "LlenÃ³sele la fantasÃ­a de todo aquello que leÃ­a en los libros, asÃ­ de encantamientos como de pendencias, batallas, desafÃ­os, heridas, requiebros, amores, tormentas y disparates imposibles.",
  "Y asentÃ³sele de tal modo en la imaginaciÃ³n que era verdad toda aquella mÃ¡quina de aquellas sonadas soÃ±adas invenciones que leÃ­a, que para Ã©l no habÃ­a otra historia mÃ¡s cierta en el mundo.",
  "DecÃ­a Ã©l que el Cid Ruy DÃ­az habÃ­a sido muy buen caballero; pero que no tenÃ­a que ver con el caballero de la Ardiente Espada, que de sÃ³lo un revÃ©s habÃ­a partido por medio dos fieros y descomunales gigantes.",
  "Mejor estaba con Bernardo del Carpio, porque en Roncesvalles habÃ­a muerto a RoldÃ¡n el encantado, valiÃ©ndose de la industria de HÃ©rcules, cuando ahogÃ³ a Anteo, el hijo de la Tierra, entre los brazos.",
  "DecÃ­a mucho bien del gigante Morgante, porque, con ser de aquella generaciÃ³n gigantea, que todos son soberbios y descomedidos, Ã©l solo era afable y bien criado.",
  "Pero sobre todos estaba bien con Reinaldos de MontalbÃ¡n, especialmente cuando le veÃ­a salir de su castillo y robar cuantos topaba, y cuando en allende robÃ³ aquel Ã­dolo de Mahoma que era todo de oro, segÃºn dice su historia.",
  "Diera Ã©l, por tener la mano a Reinaldos, al gigante FierabrÃ¡s de quien tanto se cuenta, a Bernardo del Carpio, y a todos los demÃ¡s que andaban por el mundo.",
  "Finalmente, rematado ya su juicio, vino a dar en el mÃ¡s extraÃ±o pensamiento que jamÃ¡s dio loco en el mundo, y fue que le pareciÃ³ convenible y necesario, asÃ­ para el aumento de su honra como para el servicio de su repÃºblica, hacerse caballero andante.",
  "E irse por todo el mundo con sus armas y caballo a buscar las aventuras, y a ejercitarse en todo aquello que Ã©l habÃ­a leÃ­do que los caballeros andantes se ejercitaban.",
  "Deshaciendo todo gÃ©nero de agravio, y poniÃ©ndose en ocasiones y peligros donde, acabÃ¡ndolos, cobrase eterno nombre y fama.",
  "ImaginÃ¡base el pobre ya coronado por el valor de su brazo, al menos del imperio de Trapisonda.",
  "Y asÃ­, con estos tan agradables pensamientos, llevado del extraÃ±o gusto que en ellos sentÃ­a, se dio priesa a poner en efecto lo que deseaba.",
  "Y lo primero que hizo fue limpiar unas armas que habÃ­an sido de sus bisabuelos, que, tomadas de orÃ­n y llenas de moho, largo tiempo habÃ­an estado puestas y olvidadas en un rincÃ³n.",
  "LimpiÃ³las y aderezÃ³las lo mejor que pudo, pero vio que tenÃ­an una gran falta, y era que no tenÃ­an celada de encaje, sino morriÃ³n simple.",
  "Mas a esto supliÃ³ su industria, porque de cartones hizo un modo de media celada, que, encajada con el morriÃ³n, hacÃ­a una apariencia de celada entera.",
  "Es verdad que, para probar si era fuerte y podÃ­a estar al riesgo de una cuchillada, sacÃ³ su espada y le dio dos golpes, y con el primero y en un punto la deshizo.",
  "De lo cual le pareciÃ³ no ser bien hacerse de nuevo, y, por repararla, hizo otros cartones, y, haciÃ©ndolos de nuevo, los afianzÃ³ con unas barras de hierro, de modo que quedÃ³ satisfecho de su fortaleza.",
  "Y sin querer hacer nueva experiencia dellos, los dio por celada finÃ­sima de encaje.",
  "Fue luego a ver su rocÃ­n, y aunque tenÃ­a mÃ¡s cuartos que un real y mÃ¡s tachas que el caballo de Gonela, que tantum pellis et ossa fuit, le pareciÃ³ que ni el BucÃ©falo de Alejandro ni Babieca el del Cid con Ã©l se igualaban.",
  "Cuatro dÃ­as se le pasaron en imaginar quÃ© nombre le pondrÃ­a, porque, segÃºn se decÃ­a Ã©l a sÃ­ mesmo, no era razÃ³n que caballo de caballero tan famoso, y tan bueno Ã©l por sÃ­, estuviese sin nombre conocido.",
  "Y asÃ­ procuraba acomodÃ¡rsele de manera que declarase quiÃ©n habÃ­a sido antes que fuese de caballero andante, y lo que ahora era; que estaba muy puesto en razÃ³n que, mudando su seÃ±or estado, mudase Ã©l tambiÃ©n el nombre, y le cobrase famoso y de gran sonoridad.",
  "Y asÃ­, despuÃ©s de muchos nombres que formÃ³, borrÃ³ y quitÃ³, aÃ±adiÃ³, deshizo y tornÃ³ a hacer en su memoria e imaginaciÃ³n, al cabo le vino a llamar Rocinante, nombre a su parecer alto, sonoro y significativo de lo que habÃ­a sido cuando fue rocÃ­n, antes de lo que ahora era.",
  "Puesto nombre, y tan a su gusto a su caballo, quiso ponÃ©rsele a sÃ­ mismo, y en este pensamiento durÃ³ otros ocho dÃ­as.",
  "Y al cabo se vino a llamar don Quijote, de donde, como queda dicho, tomaron ocasiÃ³n los autores desta tan verdadera historia que sin duda se debÃ­a de llamar Quijada, y no Quesada, como otros quisieron decir.",
  "Pero, acordÃ¡ndose que el valeroso AmadÃ­s no se habÃ­a contentado con llamarse sin mÃ¡s AmadÃ­s, sino que aÃ±adiÃ³ el nombre de su reino y patria, por hacerla famosa, y se llamÃ³ AmadÃ­s de Gaula, asÃ­ quiso, como buen caballero, aÃ±adir al suyo el nombre de su patria y llamarse don Quijote de la Mancha.",
  "Con esto, como queda dicho, daba a entender muy al vivo su linaje y patria, y honrÃ¡bala con tomar el sobrenombre della.",
  "Limpias, pues, sus armas, hecho del morriÃ³n celada, puesto nombre a su rocÃ­n y confirmÃ¡ndose a sÃ­ mismo, se dio a entender que no le faltaba otra cosa sino buscar una dama de quien enamorarse.",
  "Porque el caballero andante sin amores era Ã¡rbol sin hojas y sin fruto, y cuerpo sin alma.",
  "DecÃ­ase Ã©l a sÃ­: Si yo, por malos de mis pecados, o por mi buena suerte, me encuentro por ahÃ­ con algÃºn gigante, como de ordinario les acontece a los caballeros andantes, y le derribo de un encuentro, o le parto por mitad del cuerpo, o, finalmente, le venzo y le rindo, Â¿no serÃ¡ bien tener a quien enviarle presentado?",
  "Y que entre, y se hinque de rodillas ante mi dulce seÃ±ora, y le diga con voz humilde y rendida: Yo, seÃ±ora, soy el gigante Caraculiambro, seÃ±or de la Ã­nsula Malindrania, a quien venciÃ³ en singular batalla el jamÃ¡s como se debe alabado caballero don Quijote de la Mancha.",
];

export { quijoteFrases };